### ISSUE TITLE
Image harminization over multiple iteration.

### ISSUE THREAD

**Issue by RyanHangZhou** [Dominoer/bmvc2020_image_harmonization#1]
Hi, I tried using multiple iterations on one image with a fixed mask, and get a composition result with a darker color. I believe this iteration should converge until the color of the mask region shares a similiar style with the background image.

**Comment by Dominoer** [comment]
Thanks for your interest. I am not sure whether I understand your question, but are you suggesting training image harmonization on a single image? If so, did you test generalization performances on other images?

**Comment by RyanHangZhou** [comment]
> Thanks for your interest. I am not sure whether I understand your question, but are you suggesting training image harmonization on a single image? If so, did you test generalization performances on other images?

I mean suppose the initial input image is A0, the mask is M, then after image harmonization, we get A1. Then we take A1 as the input image, and fed it into the image harmonization network, and then get A2. With this kind of iteration, we should get a visually good result.

**Comment by Dominoer** [comment]
Theoretically, it should be. But my concern is that each A_N is slightly different from others, and the network will apply the same processing on different A_Ns. Anyway, thanks for your comment. This really seems an exciting direction on image harmonization, I will test this method to see if it works.

**Comment by RyanHangZhou** [comment]
Great!
